/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InteresseRouteImport } from './routes/interesse'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppCreditosRouteImport } from './routes/app.creditos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppComprarRouteImport } from './routes/app.comprar'
import { Route as AppAgendamentosRouteImport } from './routes/app.agendamentos'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminProducaoRouteImport } from './routes/admin.producao'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminPacotesRouteImport } from './routes/admin.pacotes'
import { Route as AdminDocumentosRouteImport } from './routes/admin.documentos'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InteresseRoute = InteresseRouteImport.update({
  id: '/interesse',
  path: '/interesse',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditosRoute = AppCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComprarRoute = AppComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendamentosRoute = AppAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AppRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProducaoRoute = AdminProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacotesRoute = AdminPacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentosRoute = AdminDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/interesse': typeof InteresseRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/pacotes': typeof AdminPacotesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/producao': typeof AdminProducaoRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/comprar': typeof AppComprarRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/interesse': typeof InteresseRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/pacotes': typeof AdminPacotesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/producao': typeof AdminProducaoRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/comprar': typeof AppComprarRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/interesse': typeof InteresseRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/pacotes': typeof AdminPacotesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/producao': typeof AdminProducaoRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin_/login': typeof AdminLoginRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/comprar': typeof AppComprarRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/interesse'
    | '/login'
    | '/pagamento'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/documentos'
    | '/admin/pacotes'
    | '/admin/pagamentos'
    | '/admin/producao'
    | '/admin/suporte'
    | '/admin/login'
    | '/app/agendamentos'
    | '/app/comprar'
    | '/app/configuracoes'
    | '/app/creditos'
    | '/app/equipe'
    | '/app/historico'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/interesse'
    | '/login'
    | '/pagamento'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/documentos'
    | '/admin/pacotes'
    | '/admin/pagamentos'
    | '/admin/producao'
    | '/admin/suporte'
    | '/admin/login'
    | '/app/agendamentos'
    | '/app/comprar'
    | '/app/configuracoes'
    | '/app/creditos'
    | '/app/equipe'
    | '/app/historico'
    | '/app/suporte'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/interesse'
    | '/login'
    | '/pagamento'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/documentos'
    | '/admin/pacotes'
    | '/admin/pagamentos'
    | '/admin/producao'
    | '/admin/suporte'
    | '/admin_/login'
    | '/app/agendamentos'
    | '/app/comprar'
    | '/app/configuracoes'
    | '/app/creditos'
    | '/app/equipe'
    | '/app/historico'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  InteresseRoute: typeof InteresseRoute
  LoginRoute: typeof LoginRoute
  PagamentoRoute: typeof PagamentoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interesse': {
      id: '/interesse'
      path: '/interesse'
      fullPath: '/interesse'
      preLoaderRoute: typeof InteresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creditos': {
      id: '/app/creditos'
      path: '/creditos'
      fullPath: '/app/creditos'
      preLoaderRoute: typeof AppCreditosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comprar': {
      id: '/app/comprar'
      path: '/comprar'
      fullPath: '/app/comprar'
      preLoaderRoute: typeof AppComprarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendamentos': {
      id: '/app/agendamentos'
      path: '/agendamentos'
      fullPath: '/app/agendamentos'
      preLoaderRoute: typeof AppAgendamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/producao': {
      id: '/admin/producao'
      path: '/producao'
      fullPath: '/admin/producao'
      preLoaderRoute: typeof AdminProducaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacotes': {
      id: '/admin/pacotes'
      path: '/pacotes'
      fullPath: '/admin/pacotes'
      preLoaderRoute: typeof AdminPacotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documentos': {
      id: '/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AdminDocumentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminDocumentosRoute: typeof AdminDocumentosRoute
  AdminPacotesRoute: typeof AdminPacotesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminProducaoRoute: typeof AdminProducaoRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCardapioRoute: AdminCardapioRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminDocumentosRoute: AdminDocumentosRoute,
  AdminPacotesRoute: AdminPacotesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminProducaoRoute: AdminProducaoRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAgendamentosRoute: typeof AppAgendamentosRoute
  AppComprarRoute: typeof AppComprarRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCreditosRoute: typeof AppCreditosRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendamentosRoute: AppAgendamentosRoute,
  AppComprarRoute: AppComprarRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCreditosRoute: AppCreditosRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  InteresseRoute: InteresseRoute,
  LoginRoute: LoginRoute,
  PagamentoRoute: PagamentoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
